### ISSUE TITLE
error while running import nltk

### ISSUE THREAD

**Issue by yashaswiniuma** [takuti/flurs#3] opened 2018-02-02 03:23 UTC
i have installed python,nltk .did coding related stemming .
everything was fine.
but suddenly error came by showing that 'python' is not recognized as internal and external command
reinstalled python 2.7
now while importing nltk below error is showing 
![github](https://user-images.githubusercontent.com/33446718/35715081-6708094a-07f6-11e8-964c-55a68a1780c6.png)
my project has come to end suddenly it happen 
how to resolve this 
thank you in advance

**Comment by takuti** [comment] 2018-02-02 03:43
@yashaswiniuma Thanks for reporting. I'm not sure if this error is directly related to FluRS, so could you provide entire code in `streaming_new.py`?

**Comment by yashaswiniuma** [comment] 2018-02-02 04:18
[stemming.txt](https://github.com/takuti/flurs/files/1688031/stemming.txt)

**Comment by takuti** [comment] 2018-02-06 03:29
Your code does not use my FluRS package, right? What is your problem on FluRS? If your problem is only related to NLTK import, you should ask at https://github.com/nltk/nltk/issues

**Comment by takuti** [comment] 2018-02-19 20:31
I believe the problem is not directly related to FluRS package, so I'll close this issue for now. If you find further problems or relationship between the error and this library, feel free to re-open this issue and report the detail.

**Closed by takuti** 2018-02-19 20:31 UTC
